#ifndef _CONFIG_H_
#define _CONFIG_H_

#include "filemap.h"

// General
#define DEF_USE_ATTACK_BS 1ULL
#define DEF_USE_ATTACK_WS 1ULL
#define DEF_USE_ATTACK_SS 0ULL

// mincore by default
#define DEF_FC_STATE_SOURCE FC_SOURCE_MINCORE
// readahead size (/sys/block/xxx/queue/read_ahead_kb)
#define DEF_FA_WINDOW_SIZE_PAGES 32

// Eviction Set
#define DEF_ES_USE_ANON_MEMORY 1ULL
#define DEF_ES_USE_ACCESS_THREADS 1ULL
#define DEF_ES_USE_FILE_API 0ULL
#define DEF_ES_EVICTION_FILE_PATH "eviction.ram"
#define DEF_ES_TARGETS_CHECK_ALL_X_BYTES 66617344ULL
#define DEF_ES_WS_ACCESS_ALL_X_BYTES 41570304ULL
#define DEF_ES_SS_ACCESS_ALL_X_BYTES 62357504ULL
#define DEF_ES_PREFETCH_ES_BYTES 2289664ULL
#define DEF_ES_ACCESS_THREAD_COUNT 63ULL

// Blocking Set
#define DEF_BS_FILLUP_SIZE 33554432ULL
#define DEF_BS_MIN_AVAILABLE_MEM 431771648ULL
#define DEF_BS_MAX_AVAILABLE_MEM 498880512ULL
#define DEF_BS_EVALUATION_SLEEP_TIME_US 12397ULL

// Working Set
#define DEF_WS_EVALUATION 0ULL
#define DEF_WS_EVICTION_IGNORE_EVALUATION 1ULL  
#define DEF_WS_USE_FILE_API 0ULL
char* DEF_WS_SEARCH_PATHS[] =
{
    "/bin", "/dev/shm", "/etc", /*"/home",*/ "/lib", "/opt",
    "/run", "/sbin", "/snap", "/tmp", "/usr", "/var", NULL
};
#define DEF_WS_PS_ADD_THRESHOLD 328ULL
#define DEF_WS_ACCESS_SLEEP_TIME_US 21161ULL
#define DEF_WS_EVALUATION_SLEEP_TIME_US 12840122ULL
// not implemented yet
#define DEF_WS_PROFILE_UPDATE_ALL_X_EVALUATIONS (0)    
#define DEF_WS_ACCESS_THREAD_COUNT 3ULL

// Suppress Set
#define DEF_SS_USE_FILE_API 1ULL
#define DEF_SS_ACCESS_SLEEP_TIME_US 48141ULL
#define DEF_SS_ACCESS_THREAD_COUNT 20ULL

#endif
